#!/usr/bin/env bash
set -euo pipefail

# ---------------------------------------------------------------------------
# LSP-Insights MCP Server Launcher
#
# Resolves Postgres credentials via direnv + resolve_pg_env.py, generates a
# runtime mcpls.toml config, and launches mcpls (an LSP-to-MCP bridge).
#
# Environment expected from the client .envrc:
#   PGROSERVICE   - pg_service.conf section name for the readonly connection
#
# Optional overrides:
#   MCPLS_BIN           - path to mcpls binary (auto-detected if unset)
#   PGLS_BIN            - path to postgres-language-server binary
#   MCP_LSPINSIGHTS_APPNAME - PGAPPNAME for the LSP subprocess
#   MCPLS_LOG_LEVEL     - mcpls log level (default: warn)
# ---------------------------------------------------------------------------

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TOOLKIT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
CLIENT_ROOT="${CLIENT_ROOT:-${PWD}}"
RESOLVER="${TOOLKIT_ROOT}/tools/lib/resolve_pg_env.py"

RUNTIME_DIR="${SCRIPT_DIR}/.runtime"
RUNTIME_TOML="${RUNTIME_DIR}/mcpls.toml"

# --- Dependency checks ---

if ! command -v direnv >/dev/null 2>&1; then
  echo "direnv is required for the LSP-Insights launcher" >&2
  exit 1
fi

# --- Resolve mcpls binary ---

MCPLS_BIN="${MCPLS_BIN:-}"
if [[ -z "${MCPLS_BIN}" ]]; then
  if command -v mcpls >/dev/null 2>&1; then
    MCPLS_BIN="$(command -v mcpls)"
  elif [[ -x "${SCRIPT_DIR}/bin/mcpls" ]]; then
    MCPLS_BIN="${SCRIPT_DIR}/bin/mcpls"
  fi
fi

if [[ -z "${MCPLS_BIN}" || ! -x "${MCPLS_BIN}" ]]; then
  echo "mcpls binary not found. Install it with tools/lsp-insights/install-mcpls.sh or set MCPLS_BIN." >&2
  exit 1
fi

# --- Resolve postgres-language-server binary ---

BUNDLED_PGLS_AARCH64="${HOME}/node_modules/@postgres-language-server/cli-aarch64-apple-darwin/postgres-language-server"
BUNDLED_PGLS_WRAPPER="${HOME}/node_modules/@postgres-language-server/cli/bin/postgres-language-server"

PGLS_BIN="${PGLS_BIN:-}"
if [[ -z "${PGLS_BIN}" ]]; then
  if [[ -x "${BUNDLED_PGLS_AARCH64}" ]]; then
    PGLS_BIN="${BUNDLED_PGLS_AARCH64}"
  elif [[ -x "${BUNDLED_PGLS_WRAPPER}" ]]; then
    PGLS_BIN="${BUNDLED_PGLS_WRAPPER}"
  elif command -v postgres-language-server >/dev/null 2>&1; then
    PGLS_BIN="$(command -v postgres-language-server)"
  fi
fi

if [[ -z "${PGLS_BIN}" || ! -x "${PGLS_BIN}" ]]; then
  echo "postgres-language-server binary not found. Set PGLS_BIN or install it." >&2
  exit 1
fi

# --- Load client env via direnv ---

cd "${CLIENT_ROOT}"
eval "$(direnv export bash)"

: "${PGROSERVICE:?PGROSERVICE must be exported by .envrc}"

# --- Resolve PG credentials (LSP mode: PGHOST, PGPORT, etc.) ---

eval "$(python3 "${RESOLVER}" --service "${PGROSERVICE}" --mode lsp --appname "${MCP_LSPINSIGHTS_APPNAME:-cursor-lsp-insights}")"

# Clear inherited service vars so the LSP subprocess uses explicit host/port/etc.
unset PGSERVICE
unset PGSERVICEFILE

# --- Resolve pgls config path ---
# pgls needs --config-path (or PGT_CONFIG_PATH env var) to find the
# postgres-language-server.jsonc that tells it about linting, schema, etc.

PGLS_CONFIG="${PGLSP_CONFIG:-${CLIENT_ROOT}/postgres-language-server.jsonc}"
if [[ ! -f "${PGLS_CONFIG}" ]]; then
  echo "Warning: pgls config not found at ${PGLS_CONFIG}. Schema introspection will be limited." >&2
fi

# --- Generate runtime mcpls.toml ---

mkdir -p "${RUNTIME_DIR}"

MCPLS_LOG_LEVEL="${MCPLS_LOG_LEVEL:-warn}"

cat > "${RUNTIME_TOML}" <<TOML
# Auto-generated by tools/lsp-insights/run.sh — do not edit manually.
# Regenerated on every launch with current credentials.

[workspace]

[[workspace.language_extensions]]
extensions = ["sql"]
language_id = "sql"

[[lsp_servers]]
language_id = "sql"
command = "${PGLS_BIN}"
args = ["lsp-proxy"]
file_patterns = ["**/*.sql"]

[lsp_servers.env]
PGHOST = "${PGHOST}"
PGPORT = "${PGPORT}"
PGDATABASE = "${PGDATABASE}"
PGUSER = "${PGUSER}"
PGPASSWORD = "${PGPASSWORD}"
PGSSLMODE = "${PGSSLMODE}"
PGAPPNAME = "${PGAPPNAME:-cursor-lsp-insights}"
PGT_CONFIG_PATH = "${PGLS_CONFIG}"
TOML

# Restrict permissions on the generated config (contains credentials)
chmod 600 "${RUNTIME_TOML}"

# --- Launch mcpls ---
#
# NOTE: mcpls v0.3.4 has a bug where [lsp_servers.env] values are parsed but
# never applied to the subprocess (Command::new never calls .envs()).  As a
# workaround we export the critical variables here so they are inherited by
# both mcpls and any child processes it spawns.

export MCPLS_LOG="${MCPLS_LOG_LEVEL}"
export PGT_CONFIG_PATH="${PGLS_CONFIG}"
export PGHOST PGPORT PGDATABASE PGUSER PGPASSWORD PGSSLMODE PGAPPNAME

exec "${MCPLS_BIN}" --config "${RUNTIME_TOML}"
