CREATE ROLE pgls_readonly
    LOGIN
    PASSWORD 'replace_me'
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    NOINHERIT
    NOREPLICATION;

GRANT CONNECT ON DATABASE your_database TO pgls_readonly;

GRANT USAGE ON SCHEMA public TO pgls_readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO pgls_readonly;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO pgls_readonly;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO pgls_readonly;
GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA public TO pgls_readonly;

ALTER DEFAULT PRIVILEGES FOR ROLE app_owner IN SCHEMA public
  GRANT SELECT ON TABLES TO pgls_readonly;
ALTER DEFAULT PRIVILEGES FOR ROLE app_owner IN SCHEMA public
  GRANT SELECT ON SEQUENCES TO pgls_readonly;
ALTER DEFAULT PRIVILEGES FOR ROLE app_owner IN SCHEMA public
  GRANT EXECUTE ON FUNCTIONS TO pgls_readonly;
ALTER DEFAULT PRIVILEGES FOR ROLE app_owner IN SCHEMA public
  GRANT EXECUTE ON PROCEDURES TO pgls_readonly;
